# Generated by Django 4.0.6 on 2022-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('name_of_upload', models.CharField(max_length=300)),
                ('class_of_business', models.CharField(max_length=300)),
                ('name_of_policyholder', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('policy_number', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('expected_date_of_premium_payment', models.DateField()),
                ('date_of_premium_payment', models.DateField()),
                ('premium_installment', models.FloatField()),
                ('payment_frequency', models.IntegerField()),
                ('total_premium', models.FloatField()),
            ],
        ),
    ]
