# Generated by Django 4.0.6 on 2022-08-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppa_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_doc',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
