# Generated by Django 4.0.6 on 2022-08-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppa_model', '0002_upload_doc_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='assumptions',
            fields=[
                ('name_of_assumption', models.CharField(max_length=300)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=100)),
                ('class_of_business', models.CharField(max_length=100)),
                ('discount_rate', models.FloatField()),
                ('expense_ratio', models.FloatField()),
                ('loss_ratio', models.FloatField()),
                ('risk_adjustment', models.FloatField()),
                ('acquisition_costs', models.FloatField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='upload_doc',
            name='file',
            field=models.FileField(upload_to='ppa_model/uploads/'),
        ),
    ]
