# Generated by Django 4.0.6 on 2022-08-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppa_model', '0004_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assumptions',
            name='acquisition_costs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='discount_rate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='expense_ratio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='loss_ratio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='risk_adjustment',
            field=models.CharField(max_length=100),
        ),
    ]
