# Generated by Django 4.0.6 on 2022-08-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppa_model', '0005_alter_assumptions_acquisition_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_discount_rate',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='session_loss_ratio',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='session_measurement_date',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='session_risk_adjustment',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
