# Generated by Django 4.0.6 on 2022-08-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppa_model', '0006_session_session_discount_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'get_latest_by': 'updated_at'},
        ),
    ]
